mywebsite/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('prediksi/', include("prediksi_padi.urls", namespace="prediksi_padi")),
    path('', views.index, name="index"),
    
]

prediksi_padi/urls.py
from django.urls import path
from . import views

app_name = "prediksi_padi"
urlpatterns = [
    path('download_hasil/', views.export_csv, name='export_csv'),
    path('download_hasil_pred/', views.export_csv_pred, name='export_csv_pred'),
    path("hasil_testing/<provinsi>/", views.tampil_grafik, name="hasil_filter"),
    path("hasil_testing/", views.hasil, name="hasil"),
    path("hasil_pred/<nama_provinsi>/",views.tampil_grafik_pred,name="hasil_pred_filter"),
    path("hasil_pred/",views.hasil_pred,name="hasil_pred"),
    path("data_pred/", views.data_pred, name="data_pred"),
    path("data/", views.data, name="data"),
    path("pred_input/", views.prediksi_input, name="pred_input"),
    path("load_data_pred/",views.up_data_pred, name="load_data_pred"),
    path("load_data/", views.up_data, name="load_data"),
]

prediksi_padi/models.py
from re import T
from django.db import models

# Create your models here.
class training_testing(models.Model):
    provinsi = models.CharField(max_length=50)
    kode_provinsi = models.IntegerField()
    bulan_tahun = models.DateField()
    luas_panen = models.FloatField()
    produktivitas = models.FloatField()
    produksi = models.FloatField()
    curah_hujan = models.FloatField()
    hari_hujan = models.IntegerField()

    def __str__(self):
        return f"{self.provinsi} - {self.bulan_tahun}"

class predict(models.Model):
    provinsi = models.CharField(max_length=50)
    kode_provinsi = models.IntegerField()
    bulan_tahun = models.DateField()
    luas_panen = models.FloatField()
    produktivitas = models.FloatField()
    curah_hujan = models.FloatField()
    hari_hujan = models.IntegerField()
    produksi = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f"{self.provinsi} - {self.bulan_tahun}"

prediksi_padi/forms.py
from django import forms

class UploadFileForm(forms.Form):
    data_csv = forms.FileField(
        widget = forms.FileInput(
              attrs = {
                'class':'custom-file-input',
                'accept':'text/csv'
            }
        )
    )

class PredictForm(forms.Form):
    provinsi = forms.CharField(
        widget= forms.TextInput(
            attrs= {
                'class':'custom-select mr-sm-',
            }
        )
    )
    kode_provinsi = forms.IntegerField(
        widget= forms.NumberInput(
            attrs= {
                'class':'custom-select mr-sm-',
            }
        )
    )
    bulan_tahun = forms.DateField(
        widget= forms.DateInput(
            attrs= {
                'class':'form-control',
                'type': 'date',

               
            }
            
        )
    )
    #  bulan_tahun = forms.DateField(
    #     widget= forms.SelectDateWidget(
    #         years = range(2018,2029,1),
    #         attrs= {
    #             'class':'form-control col-sm-2',
    #              'style': 'display: inline-block;', 
               
    #         }
            
    #     )
    # )
    luas_panen = forms.FloatField(
        widget= forms.NumberInput(
            attrs= {
                'class':'form-control',
                'placeholder':'Luas Panen'
            }
        )
    )  
    produktivitas = forms.FloatField(
         widget= forms.NumberInput(
            attrs= {
                'class':'form-control',
                'placeholder':'Produktivitas'
            }
        )
    )
    curah_hujan = forms.FloatField(
         widget= forms.NumberInput(
            attrs= {
                'class':'form-control',
                'placeholder':'Curah Hujan'
            }
        )
    )
    hari_hujan = forms.IntegerField(
         widget= forms.NumberInput(
            attrs= {
                'class':'form-control',
                'placeholder':'Hari Hujan'
            }
        )
    )

prediksi_padi/views.py
from asyncio.windows_events import NULL
from datetime import datetime
from email import message
import imp
from django.http import HttpResponse
from importlib.metadata import files
from multiprocessing import context
from urllib import response
from django.shortcuts import render, redirect
from .forms import UploadFileForm, PredictForm
from .models import training_testing, predict
import csv
from django.contrib import messages
from io import TextIOWrapper
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import joblib
import numpy as np 
import pandas as pd
from .pemodelan import split_data, model_xgboost, mean_absolute_percentage_error, accuracy

# Views Prediksi Padi

# prediksi dari input
def prediksi_input(request):
    prov = training_testing.objects.values_list('provinsi','kode_provinsi').distinct()
    prediksi_form = PredictForm(request.POST or None)
    df = None
    if request.method == 'POST':
        prediksi_form = PredictForm(request.POST)
        if prediksi_form.is_valid():
            provinsi = prediksi_form.cleaned_data.get('provinsi')
            kode_provinsi = prediksi_form.cleaned_data.get('kode_provinsi')
            bulan_tahun = prediksi_form.cleaned_data.get('bulan_tahun')
            luas_panen = prediksi_form.cleaned_data.get('luas_panen')
            produktivitas = prediksi_form.cleaned_data.get('produktivitas')
            curah_hujan = prediksi_form.cleaned_data.get('curah_hujan')
            hari_hujan = prediksi_form.cleaned_data.get('hari_hujan')

            # print("Data Provinsi:", provinsi)
            # print("Kode Provinsi:", kode_provinsi)

            data = {
                'provinsi': provinsi,
                'kode_provinsi': kode_provinsi,
                'bulan_tahun': bulan_tahun,
                'luas_panen': luas_panen,
                'produktivitas': produktivitas,
                'curah_hujan': curah_hujan,
                'hari_hujan': hari_hujan,
                'produksi':None,
            }

            df = pd.DataFrame(data, index=[0])
            var_input = df[['kode_provinsi', 'luas_panen', 'produktivitas', 'curah_hujan','hari_hujan']]

            # prediksi dengan xgboost
            xgb_jl = joblib.load('prediksi_padi/model_ml/xgb_joblib.joblib')
            prediksi = xgb_jl.predict(var_input)
            df['produksi'] = prediksi.round(2)
            print(df)

            # Simpan data ke dalam database
            for index, row in df.iterrows():
                prediksi_data = predict(
                    provinsi=row['provinsi'],
                    kode_provinsi=row['kode_provinsi'],
                    bulan_tahun=row['bulan_tahun'],
                    luas_panen=row['luas_panen'],
                    produktivitas=row['produktivitas'],
                    curah_hujan=row['curah_hujan'],
                    hari_hujan=row['hari_hujan'],
                    produksi=row['produksi']
                )
                prediksi_data.save()
            messages.success(request, 'Data berhasil diunggah')
        else:
            messages.error(request, 'Data tidak sesuai')
    else:
         post_form = UploadFileForm(request.POST)
    context = {
        'title':'Data Padi Prediksi Input',
        'prediksi_css':'prediksi/css/styles.css',
        'pred_form':prediksi_form,
        'provinsi':prov,
        'hasil_pred':df['produksi'][0] if df is not None else None,
    }
    
    return render(request, 'prediksi/prediksi.html', context)

# mendowload file csv hasil prediksi 
def export_csv_pred(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="data_prediksi_padi.csv"'

    writer = csv.writer(response)
    writer.writerow(['id','provinsi','kode_provinsi','bulan_tahun','luas_panen','produktivitas','curah_hujan','hari_hujan','prediksi_produksi'])

    # data 
    data = predict.objects.all()
    prediksi = pd.DataFrame(data.values())
    # data_unduh = prediksi.values_list('provinsi','kode_provinsi','bulan_tahun','luas_panen','produktivitas','curah_hujan','hari_hujan','prediksi_produksi')
    data_unduh = prediksi.to_numpy()
    for hasil in data_unduh:
        writer.writerow(hasil)

    return response

# menampilkan grafik data prediksi per provinsi 
def tampil_grafik_pred(request,nama_provinsi):
    # data training & testing
    data_traintest = training_testing.objects.all()
    pred_traintest = model_xgboost(data_traintest.values())

    # prediksi data baru 
    data = predict.objects.all()
    xgb_jl = joblib.load('prediksi_padi/model_ml/xgb_joblib.joblib')
    df = pd.DataFrame(data.values())
    var_input = df[['kode_provinsi', 'luas_panen','produktivitas','curah_hujan','hari_hujan']]

    # prediksi dengan xgboost
    prediksi = xgb_jl.predict(var_input)

    # update kolom produksi dengan data hasil prediksi
    for i, data_padi in enumerate(data,):
        data_padi.produksi = prediksi[i]
    predict.objects.bulk_update(data, ['produksi'])

    # mengambil data hasil prediksi 
    data_hasil = predict.objects.filter(provinsi=nama_provinsi)

    # filter provinsi
    nama_prov = df['provinsi'].unique()
    prov = nama_provinsi
    filter_data = df[df['provinsi'] == nama_provinsi ]
    data_produksi = list(filter_data['produksi'])
    print(data_produksi)

    # filter data training untuk mape & akurasi
    filter_data_train = pred_traintest[pred_traintest['provinsi'] == nama_provinsi]

    # menghitung nilai mape & akurasi
    mape = mean_absolute_percentage_error(filter_data_train['produksi'],filter_data_train['prediksi_produksi'])
    akurasi = accuracy(mean_absolute_percentage_error(filter_data_train['produksi'],filter_data_train['prediksi_produksi']))
    
    context = {
        'title':'Hasil Prediksi Padi',
        'prediksi_css':'prediksi/css/styles.css',
        'data_hasil': data_hasil,
        'nama_prov':nama_prov,
        'prov':prov,
        'data_prediksi':data_produksi,
        'nilai_mape':mape,
        'nilai_akurasi':akurasi
    }
    return render(request, 'prediksi/hasil_pred.html', context)

# menampilkan data hasil prediksi
def hasil_pred(request):
    # data training & testing
    data_traintest = training_testing.objects.all()
    pred_traintest = model_xgboost(data_traintest.values())

    # prediksi data baru 
    data = predict.objects.all()
    xgb_jl = joblib.load('prediksi_padi/model_ml/xgb_joblib.joblib')
    df = pd.DataFrame(data.values())
    var_input = df[['kode_provinsi','luas_panen','produktivitas','curah_hujan','hari_hujan']]

    # prediksi dengan xgboost
    prediksi = xgb_jl.predict(var_input)

    # prediksi dengan xgboost 
    for i, data_padi in enumerate(data,):
        data_padi.produksi = prediksi[i]
    predict.objects.bulk_update(data, ['produksi'])

    # mengambil data hasil prediksi 
    data_hasil = predict.objects.all()
    df_hasil = pd.DataFrame(data_hasil.values())

    # menghitung mape dan akurasi 
    mape = mean_absolute_percentage_error(pred_traintest['produksi'],pred_traintest['prediksi_produksi'])
    akurasi = accuracy(mean_absolute_percentage_error(pred_traintest['produksi'],pred_traintest['prediksi_produksi']))

    nama_prov = df_hasil['provinsi'].unique()
    # kondervsi ke tipe datetimelike
    df_hasil['bulan_tahun'] = pd.to_datetime(df_hasil['bulan_tahun'])
    # mengelompokkan berdasarkan bulan dan hitung total produksi 
    df_hasil['bulan_tahun'] = df_hasil['bulan_tahun'].dt.to_period('M')
    data_prediksi = list(df_hasil.groupby('bulan_tahun')['produksi'].sum())
    print(df_hasil)
    print(data_prediksi)
  
    context = {
        'title':'Hasil Prediksi Padi',
        'prediksi_css':'prediksi/css/styles.css',
        'data_hasil': data_hasil,
        'nama_prov':nama_prov,
        'data_prediksi':data_prediksi,
        'nilai_mape':mape,
        'nilai_akurasi':akurasi
    }
    # print(context)
    return render(request, 'prediksi/hasil_pred.html', context)

# menampilkan data hasil upload data prediksi baru
def data_pred(request):
    data = predict.objects.all()
    p = Paginator(data,10)
    page = request.GET.get('page',1)
    p = Paginator(data, 10)
    try :
        hasil_data = p.page(page)
    except PageNotAnInteger:
        hasil_data = p.page(1)
    except EmptyPage:
        hasil_data = p.page(p.num_pages)
    context = {
        'title':'Data Prediksi Padi Upload',
        'prediksi_css':'prediksi/css/styles.css',
        'pagination':hasil_data,
    }           
    return render(request, 'prediksi/data_pred.html', context)

# memasukkan dari file csv ke database Testing
def handle_uploaded_file_pred(data_clean):
    result_data_save = []
    for row in data_clean:
        predict.objects.create(
            provinsi = row['provinsi'],
            kode_provinsi = row['kode_provinsi'],
            bulan_tahun = row['bulan_tahun'],
            luas_panen = row['luas_panen'],
            produktivitas = row['produktivitas'],
            # produksi = row['produksi'], ## variabel target
            curah_hujan = row['curah_hujan'],
            hari_hujan = row['hari_hujan'],
            )
        result_data_save.append(row)   
    return result_data_save

# cleaning data Prediksi
def clean_data_csv_pred(file):
    result_clean_data = []
    required_column = ['\ufeffprovinsi', 'kode_provinsi', 'bulan_tahun', 'luas_panen', 'produktivitas','produksi', 'curah_hujan', 'hari_hujan']
    with TextIOWrapper(file, encoding='utf-8') as file_wrapper:
        reader = csv.DictReader(file_wrapper, delimiter=';')
        for row in reader:
             # Membersihkan karakter BOM pada kunci 'provinsi'
            if all(col in row for col in required_column):
                cleaned_provinsi = row.pop('\ufeffprovinsi', None) if '\ufeffprovinsi' in row else row.get('provinsi')
                row['provinsi'] = cleaned_provinsi

                row['bulan_tahun'] = datetime.strptime(row['bulan_tahun'], '%m/%d/%Y').strftime('%Y-%m-%d')

prediksi_padi/templates/prediksi/hasil.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="jumbotron jumbotron-fluid" style="height: auto;">
  <div class="container">
    <div class="row mt-md-3 justify-content-center">
      <div class="col-md-7">
        <div class="card mb-0">
          <div class="card-header">
            <div class="row">
              <div class="col-12 col-md-6 mb-2 mb-md-0">
                <div class="dropdown">
                  <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Semua Provinsi
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">  
                      {% for provinsi in nama_prov  %}
                        <a class="dropdown-item" href="{% url 'prediksi_padi:hasil_filter' provinsi %}" onclick="updateChart('{{ provinsi }}')">{{ provinsi }}</a>
                      {% endfor %}
                  </div>
                </div>
              </div>
              <div class="col-12 col-md-6">
                Prediksi Hasil Padi 
                <strong>
                  {% if prov %}
                    {{ prov }}
                  {% endif %}
                </strong>
              </div>
            </div>
          </div>
          <div class="card-body text-secondary">
            <canvas id="myChart"></canvas>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
      <div class="col-md-5 mt-3 mt-md-0">
        <div class="row text-center">
          <div class="col-12 col-md-6 mb-1">
            <div class="card mb-1">
              <div class="card-header text-white" style="background-color: #c1121f"> Nilai MAPE</div>
              <div class="card-body">
                <h2 class="card-title">{{ nilai_mape | floatformat:2 }} %</h2>
              <p class="card-text">Tingkat Kesalahan Prediksi</p>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6 mb-1">
            <div class="card mb-1">
              <div class="card-header bg-success text-white">Nilai Akurasi</div>
              <div class="card-body">
                <h2 class="card-title"> {{ nilai_akurasi | floatformat:2 }} %</h2>
                <p class="card-text">Tingkat Nilai Akurasi Prediksi</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12 col-md-12 mb-1">
            <div class="card mb-3">
              <div class="card-body">
                <!-- <p>Kriteria Nilai MAPE</p> -->
                <table class="table table-sm">
                  <thead>
                    <tr>
                      <th scope="col"></th>
                      <th scope="col">Skala MAPE</th>
                      <th scope="col"></th>
                      <th scope="col">Kriteria</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">1</th>
                      <td> &lt; 10%</td>
                      <td></td>
                      <td>Sangat Baik</td>
                    </tr>
                    <tr>
                      <th scope="row">2</th>
                      <td>10% - 20%</td>
                      <td></td>
                      <td>Baik</td>
                    </tr>
                    <tr>
                      <th scope="row">3</th>
                      <td colspan="2">20% - 50%</td>
                      <td>Cukup</td>
                    </tr>
                    <tr>
                      <th scope="row">4</th>
                      <td colspan="2"> &gt; 50%</td>
                      <td>Buruk</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            
          </div>
        </div>
      </div>
      
      <div class="col-md-12">
        <!-- <p class="format">*format file .csv</p>
        <a class="btn btn-warning float-md-left" href="{% url 'prediksi_padi:export_csv' %}">Download</a> -->
        <div class="table-responsive">
          <table class="table table-active table-bordered table-sm">
            <thead>
              <tr>
                <th scope="col">No</th>
                <th scope="col">Provinsi</th>
                <th scope="col">Kode Provinsi</th>
                <th scope="col">Bulan Tahun</th>
                <th scope="col">Luas Panen </th>
                <th scope="col">Produktivitas</th>
                <th scope="col">Produksi</th> 
                <th scope="col">Curah Hujan</th>
                <th scope="col">Hari Hujan</th>
                <th scope="col" class="col-pred">Prediksi</th>
              </tr>

              <!-- <tr>
                
                {% for column in data_hasil.columns %}
                  <th>{{ column }}</th>
                {% endfor %}
                  
              </tr> -->

            </thead>
            <tbody>
<!-- 
              {% for index, row in data_hasil.iterrows  %}
                <tr>
                  {% for value in row %}
                    <td>{{value}}</td>
                  {% endfor %}
                </tr>
              {% endfor %} -->

              
              {% for index, row in data_hasil.iterrows %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  
                  {% for column, value in row.iteritems %}
                    
                    {% if column != 'id' %}

                      {% if column == 'bulan_tahun' %}
                        <td> {{value|date:"F Y"}} </td>
                      {% elif column == 'prediksi_produksi' %}
                      <td class="col-hsl"> {{value|floatformat:"2"}} </td>
                      {% else %}
                        <td>{{value}}</td>
                      {% endif %}

                    {% endif %}
                    
                  {% endfor %}
                    
                </tr>
              {% endfor %}
                
            </tbody>
          </table>
        </div>
       
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block script%}
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    // data: {
    //     labels: ['January', 'February', 'March', 'April', 'May', 'June', 'Juli', 'Agustus', 'September', 'Oktober','November','Desember'],
    //     datasets: [{
    //         label: 'My First Dataset',
    //         data: {{ data_produksi }},
    //         fill: false,
    //         borderColor: '#28a745',
    //         tension: 0.1
    //     }]
    // },
    

    data: {
      labels: ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'],
      datasets: [{
        label: 'Produksi',
        data: {{ data_produksi}},
        fill: false,
        borderColor: '#28a745',
        tension: 0.1
      },
      {
        label: 'Prediksi',
        data: {{data_prediksi}},
        fill: false,
        borderColor: '#f7b801',
        tension: 0.1
      }
    ]
    },

    options: {
        maintainAspectRatio: false, // Menonaktifkan pengaturan otomatis rasio aspek
        aspectRatio: 0.9, // Mengatur rasio aspek sesuai kebutuhan 
        scales: {
            y: {
                suggestedMin: 10,
                suggestedMax: 20
            }
        }
    }
});

</script>

<!-- <script>
  var ctx = document.getElementById('myChart').getContext('2d');
  var myChart;

  function updateChart(selectProvinsi) {
    var dataProduksi = fetchData(selectProvinsi, 'produksi');
    var dataPrediksi = fetchData(selectProvinsi, 'prediksi_produksi');

    myChart.data.datasets[0].data = dataPrediksi;
    myChart.data.datasets[1].data = dataPrediksi;
    myChart.update()
  }
  
  function fetchData(selectProvinsi, field){
  
  }

  myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'],
      datasets: [{
        label: 'Produksi',
        data: [],
        fill: false,
        borderColor: '#28a745',
        tension: 0.1
      },
      {
        label: 'Prediksi',
        data: [],
        fill: false,
        borderColor: '#007bff',
        tension: 0.1
      }
    ]
    },
    options: {
      maintainAspectRatio: false,
      aspectRatio: 1.5,
      scales: {
        y: {
          suggestedMin: 35,
          suggestedMax: 80
        }
      }
    }
  });
  
  updateChart('Semua Provinsi')
</script> -->

{% endblock script%}

prediksi_padi/templates/prediksi/prediksi.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="jumbotron jumbotron-fluid" style="height: auto;">
  <div class="container">
    <h5 class="up mb-1">Prediksi Hasil Panen Padi</h5>
    <h6 class="up-1 mb-1">Sistem melakukan prediksi hasil padi pada tingkat <strong>Provinsi</strong> dan dalam rentang waktu </h6> 
    <h6 class="display-7">Variabel yang digunakan untuk Prediksi adalah seperti ini:</h6>
    
    <div class="row">
      <div class="col-12 col-md-5">
        <div class="table-responsive">
          <table class="table table-bordered table-active table-sm mb-1">
            <thead>
              <tr>
                <th scope="col">provinsi</th>
                <th scope="col">kode_provinsi</th>
                <th scope="col">bulan_tahun</th>
                <th scope="col">tahun</th>
                <th scope="col">luas_Panen </th>
                <th scope="col">produktivitas</th>
                <th scope="col">curah_hujan</th>
                <th scope="col">hari_hujan</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Aceh</td>
                <td>11</td>
                <td>Januari</td>
                <td>2018-01-01</td>
                <td>125470.00</td>
                <td>45.57</td>
                <td>290</td>
                <td>25</td>
              </tr>
              <tr>
                <td>Aceh</td>
                <td>11</td>
                <td>Februari</td>
                <td>2018-02-01</td>
                <td>125470.00</td>
                <td>45.57</td>
                <td>290</td>
                <td>25</td>
              </tr>
              <tr>
                <td>Aceh</td>
                <td>11</td>
                <td>Maret</td>
                <td>2018-03-01</td>
                <td>125470.00</td>
                <td>45.57</td>
                <td>290</td>
                <td>25</td>
              </tr>
            </tbody>
          </table>
        </div> 
      </div>
      <div class="col-12 col-md-7">
        <!-- <form method="post">
          {% csrf_token %}
          <table>
            {{pred_form.as_table}}
          </table>
          <button type="submit" class="btn btn-warning">Prediksi</button>
        </form> -->

        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <div class="row">
             <div class="col">
               {{ pred_form.provinsi.label_tag }}
               <select class="custom-select mr-sm-2" id="id_provinsi" name="provinsi">
                  <option selected>Provinsi</option>
                  {% for prov in provinsi  %}
                    <option value="{{prov.0}}">{{prov.0}}</option>
                  {% endfor %}
                </select>
             </div>
             <div class="col">
               {{ pred_form.kode_provinsi.label_tag }}
               <select class="custom-select mr-sm-2" id="id_kode_provinsi" name="kode_provinsi">
                <option selected>Kode Provinsi</option>
                {% for kode in provinsi  %}
                  <option value="{{kode.1}}">{{kode.1}}</option>
                {% endfor %}
              </select>
             </div>
            </div>
           <div class="row">
             <div class="col">
               {{ pred_form.bulan_tahun.label_tag }}
               {{ pred_form.bulan_tahun}}
             </div>
             <div class="col">
               {{ pred_form.luas_panen.label_tag }}
               {{ pred_form.luas_panen }}
             </div>
           </div>
           <div class="row">
             <div class="col">
               {{ pred_form.produktivitas.label_tag }}
               {{ pred_form.produktivitas }}
             </div>
             <div class="col">
               {{ pred_form.curah_hujan.label_tag }}
               {{ pred_form.curah_hujan }}
             </div>
           </div>
           <div class="row">
             <div class="col">
               {{ pred_form.hari_hujan.label_tag }}
               {{ pred_form.hari_hujan }}
             </div>
             <div class="col">
              
             </div>
           </div>
           <button type="submit" class="btn btn-warning mt-2">Prediksi</button>
         </div>
        </form>
       
        <!-- <form method="post">
          {% csrf_token %}
          <div class="form-group">
            {% for input in pred_form %}
            {% if forloop.counter0|divisibleby:2 %}
              <div class="form-row">
            {% endif %}
            <div class="col">
              {{ input.label_tag }}
              {{ input }}
            </div>
            {% if forloop.counter|divisibleby:2 or forloop.last %}
              </div>
            {% endif %}
          {% endfor %}
          </div>
          <button type="submit" class="btn btn-warning mt-2">Prediksi</button>
        </form> -->
        <div class="form-group row mr-2">
          <label for="inputProduksi" class="col-sm-2 col-form-label">Produksi</label>
          <div class="col-sm-6">
              <input type="text" class="form-control" id="inputProduksi" placeholder="Prediksi Produksi" value="{{ hasil_pred }}">
          </div>
      </div>
    </div>

    

    
  </div>
</div>
{% endblock content %}

{% block script %}

<!-- <script>
  document.getElementById('provinsiSelect').addEventListener('change', function() {
    var selectedValue = this.value;
    var secondTextField = document.getElementById('kodeProvinsiSelect');
    
    // Lakukan operasi untuk mengisi nilai text field kedua berdasarkan nilai yang dipilih dari dropdown
    // Misalnya, jika data tuple adalah array of arrays, Anda dapat mencocokkan nilai pertama dengan nilai yang dipilih dari dropdown
    // dan mengambil nilai kedua untuk diisi ke text field kedua
    // Contoh:
    var tupleData = [[1, 'Nilai 1'], [2, 'Nilai 2'], [3, 'Nilai 3']];
    var selectedTuple = tupleData.find(tuple => tuple[0] == selectedValue);
    
    if (selectedTuple) {
        secondTextField.value = selectedTuple[1];
    } else {
        secondTextField.value = '';
    }
});
</script> -->
<script>
  var provinsiData = [
    {% for prov in provinsi %}
      ['{{ prov.0 }}', '{{ prov.1 }}'],
    {% endfor %}
  ];

  document.getElementById('id_provinsi').addEventListener('change', function() {
    var selectedValue = this.value;
    var secondTextField = document.getElementById('id_kode_provinsi');
    
    var selectedTuple = provinsiData.find(tuple => tuple[0] == selectedValue);
    
    if (selectedTuple) {
        secondTextField.value = selectedTuple[1];
    } else {
        secondTextField.value = '';
    }
  });
</script>


{% endblock script %}
  
    