mywebsite/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('prediksi/', include("prediksi_padi.urls", namespace="prediksi_padi")),
    path('', views.index, name="index"),
    
]

prediksi_padi/urls.py
from django.urls import path
from . import views

app_name = "prediksi_padi"
urlpatterns = [
    path('download_hasil/', views.export_csv, name='export_csv'),
    path('download_hasil_pred/', views.export_csv_pred, name='export_csv_pred'),
    path("hasil_testing/<provinsi>/", views.tampil_grafik, name="hasil_filter"),
    path("hasil_testing/", views.hasil, name="hasil"),
    path("hasil_pred/<nama_provinsi>/",views.tampil_grafik_pred,name="hasil_pred_filter"),
    path("hasil_pred/",views.hasil_pred,name="hasil_pred"),
    path("data_pred/", views.data_pred, name="data_pred"),
    path("data/", views.data, name="data"),
    path("pred_input/", views.prediksi_input, name="pred_input"),
    path("load_data_pred/",views.up_data_pred, name="load_data_pred"),
    path("load_data/", views.up_data, name="load_data"),
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static prediksi_css %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
    <link href="{% static 'vendor/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    {% include "layouts/navbar.html" %}

    {% block content %}

    {% endblock content %}
     
    <script src="{% static 'vendor/jquery/jquery.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/popper/popper.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.js' %}" type="text/javascript"></script> 
    <script src="{% static 'vendor/jquery/chart.js' %}"></script> 
    {% block script%}

    {% endblock script%}
    
</body>
</html>

templates/layouts/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/"> 
      <img id="logo" src="{% static 'img/logo.png' %}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'prediksi_padi:load_data' %}">Training</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'prediksi_padi:load_data_pred' %}">Prediksi</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'prediksi_padi:pred_input' %}">Prediksi Provinsi</a>
        </li>
      </ul>
    </div>
</nav>